name: Deploy to Appwrite

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Appwrite CLI
      run: npm install -g appwrite

    - name: Deploy to Appwrite
      run: |
        npx appwrite deploy function --functionId 666deb45001a4115445e --projectId 666de56d00361079f322 --endpoint 'https://cloud.appwrite.io/v1' --key ${{ secrets.APPWRITE_API_KEY }}
      env:
        APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}

